# Role & binding for K8s secrets injection
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secrets-access
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: [ "get", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
  name: secrets-access-binding
subjects:
  - kind: ServiceAccount
    namespace: {{ TEST_APP_NAMESPACE_NAME }}
    name: {{ TEST_APP_SA }}
roleRef:
  kind: ClusterRole
  name: secrets-access
  apiGroup: rbac.authorization.k8s.io
