---
apiVersion: v1
kind: Service
metadata:
  name: secretless-db
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: secretless-db
  type: ClusterIP

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: secretless-db-pg
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
  labels:
    app: secretless-db
spec:
  replicas: 1
  serviceName: secretless-db
  selector:
    matchLabels:
      app: secretless-db
  template:
    metadata:
      labels:
        app: secretless-db
    spec:
      containers:
      - name: secretless-db
        image: registry.redhat.io/rhscl/postgresql-10-rhel7
        imagePullPolicy: Always
        env:
          - name: POSTGRESQL_USER
            value: demoapp
          - name: POSTGRESQL_PASSWORD
            value: test123
          - name: POSTGRESQL_DATABASE
            value: demoapp
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          initialDelaySeconds: 120
          timeoutSeconds: 10
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          initialDelaySeconds: 5
          timeoutSeconds: 1
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log