---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ SECRETLESS_SA }}
  namespace: {{ TEST_APP_NAMESPACE_NAME }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: secretless-config
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
data:
  secretless.yml: |
    version: "2"
    services:
      postgres-db:
        protocol: pg
        listenOn: tcp://0.0.0.0:5432 # can be a socket as well (same name for both)
        credentials:
          host: 
            from: conjur
            get: secretless/host
          port: 
            from: conjur
            get: secretless/port
          username:
            from: conjur
            get: secretless/username
          password:
            from: conjur
            get: secretless/password
          sslmode: disable
        config:  # this section usually blank
          optionalStuff: foo
  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secretless
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
  labels:
    app: secretless
spec:
  replicas: 1
  selector:
    matchLabels:
      role: demo
      app: secretless
  template:
    metadata:
      labels:
        role: demo
        app: secretless
    spec:
      serviceAccountName: {{ SECRETLESS_SA }}
      shareProcessNamespace: true
      containers:
      - name: secretless-broker
        image: {{ SECRETLESS_BROKER_IMAGE }}
        args: ["-f", "/etc/secretless/secretless.yml"]
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: CONJUR_APPLIANCE_URL
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_APPLIANCE_URL
          - name: CONJUR_AUTHN_URL
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP }}
                key: conjur-authn-url
          - name: CONJUR_ACCOUNT
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_ACCOUNT
          - name: CONJUR_AUTHN_LOGIN
            valueFrom:
              configMapKeyRef:
                name: {{ APP_CONFIG_MAP }}
                key: conjur-authn-login-secretless
          - name: CONJUR_SSL_CERTIFICATE
            valueFrom:
              configMapKeyRef:
                name: {{ CONJUR_CONFIG_MAP }}
                key: CONJUR_SSL_CERTIFICATE
        volumeMounts:
          - mountPath: /etc/secretless
            name: config
            readOnly: true
          - mountPath: /run/conjur
            name: conjur-access-token
      - name: demoapp
        image: cyberark/demo-app:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /pets
            port: http
          initialDelaySeconds: 15
          timeoutSeconds: 5
        env:
          - name: DB_URL
            value: "postgresql://localhost:5432/demoapp"
          - name: DB_PLATFORM
            value: postgres
      #imagePullSecrets:
        #- name: dockerpullsecret-secretless-account
      volumes:
        - name: conjur-access-token
          emptyDir:
            medium: Memory
        - name: config
          configMap:
            name: secretless-config
            defaultMode: 420